version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      MONGO_URI: mongodb://database:27017/TMT

  database:
    image: mongo
    ports:
      - "27017:27017"
